set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'preservim/nerdtree'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'itchyny/lightline.vim'
Plugin 'preservim/nerdcommenter'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-surround'

call vundle#end()            " required
filetype plugin indent on    " required

packadd! matchit

syntax on

set nobackup
set nowritebackup
set noswapfile

set hidden

set term=xterm

set number

set nowrap

set cursorline

set autoindent expandtab tabstop=4 shiftwidth=4

set listchars=eol:$,tab:->,space:·,extends:>,precedes:<
set list

set splitright
set splitbelow

set showcmd

set complete+=kspell

let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ }

let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ], [ 'readonly', 'absolutepath', 'modified' ] ],
      \ }
      \ }

set background=dark

set laststatus=2

colorscheme monokai 

vnoremap <C-c> "+y
nnoremap <leader>cf :let @+=expand('%')<CR>
nnoremap <C-Up> :m -2<CR>
nnoremap <C-Down> :m +1<CR>
nnoremap <leader>nt :NERDTreeToggle<CR>
nnoremap <leader>ntf :NERDTreeFind<CR>
